/*
 * Copyright 2014 Antonio López Marín.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package categoriplus.vista.paneles;

import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 * Panel Principal donde contiene el JTabbedPane, que añade y quita tabs.
 * 
 * @author Antonio López Marín
 */
public class PanelPrincipal extends javax.swing.JPanel{

    /**
     * Creates new form Principal
     */
    public PanelPrincipal() {
        initComponents();
        configComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();

        tabbedPane.setName("tabbedpane"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
    
    private JPanel inicio;
    
    /**
     * Metodo que configura los componentes del panel.
     * 
     */
    private void configComponents() {
        //Para que el panel se haga scroll si hay muchos 
        tabbedPane.setTabLayoutPolicy(JTabbedPane.SCROLL_TAB_LAYOUT);
        
        //creo el panel de inicio
        inicio = new JPanel(new BorderLayout());
        //Creo la imagen flecha
        
        JLabel flecha = new JLabel(java.util.ResourceBundle.getBundle("lang/lenguajes").getString("selecciona_empezar"),
                new ImageIcon("src/images/flecha.png"), JLabel.CENTER);
//        JLabel flecha = new JLabel(java.util.ResourceBundle.getBundle("lang/lenguajes").getString("selecciona_empezar"),
//                new ImageIcon(ClassLoader.getSystemResource("images/flecha.png")), JLabel.CENTER);
        flecha.setVerticalAlignment(JLabel.TOP);
        //Y la añado
        inicio.add(flecha, BorderLayout.WEST);
        //Creo la imagen de la empresa
//        JLabel imagen = new JLabel(new ImageIcon(ClassLoader.getSystemResource("images/sospresa.png"))); 
        JLabel imagen = new JLabel(new ImageIcon("src/images/sospresa.png")); 
        imagen.setVerticalAlignment(JLabel.BOTTOM);
        //Añado la imagen
        inicio.add(imagen, BorderLayout.EAST);          

        //Pongo el tabb por defecto que es inicio
        defaultTabb();
    }
        
    /**
     * Metodo que ejecuta el Tab por defecto que es el de Inicio
     */
    public void defaultTabb(){
        tabbedPane.add(java.util.ResourceBundle.getBundle("lang/lenguajes").getString("INICIO"), inicio);
    }
    
    /**
     * Devuelve el primer panel de el tabbedPane
     * @return 
     */
    public JPanel getFirstTab(){
        return (JPanel)tabbedPane.getComponentAt(0);
    }
    
    /**
     * Cambia el panel del primer Tab.
     * 
     * @param title
     * @param panel 
     */
    public void cambiarPanel(String title, JPanel panel){
        tabbedPane.setTabComponentAt(0, new JLabel(title));   
        tabbedPane.setComponentAt(0, panel);
        tabbedPane.setSelectedIndex(0); //Selecciono
    }    
    
    /**
     * Añade un panel.
     * 
     * @param title
     * @param panel 
     */
    public void addTab(String title, JPanel panel){
        tabbedPane.add(title, panel);
        tabbedPane.setSelectedComponent(panel);
    }
    
    /**
     * Borra un panel.
     * 
     * @param panel 
     */
    public void removeTab(JPanel panel){
            tabbedPane.remove(panel);
        //Si no hay paneles pone el de informacion
        if (tabbedPane.getTabCount() == 0) {
            defaultTabb();
        }
    }
    
    /**
     * Metodo que selecciona el panel que se le pasa por parametros.
     * 
     * @param panel 
     */
    public void setSelectPane(JPanel panel){
        tabbedPane.setSelectedComponent(panel);
    }
}
